language: node_js
node_js:
  - "8"

script:
  - yarn build
  - cd functions
  - yarn prepare
  - cd ../

deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change