image: node:8.1.2
options:
  max-time: 15
pipelines:
  default:
    - step:
        name: Build Cloud Functions
        script:
          - cd ./functions
          - npm i
    - step:
        name: Build main application
        script:
          - npm i
          - npm test
          - npm build
  branches:
    master:
      - step:
          name: Build Cloud Functions
          script:
            - cd ./functions
            - npm i
            - cd ../
          artifacts:
            - functions/**
      - step:
          name: Deploy Cloud Functions
          script:
            - npm i -g firebase-tools
            - firebase deploy --token $FIREBASE_TOKEN --non-interactive --only functions
      - step:
          name: Build main application
          script:
            - npm i
            - npm test
            - npm build
          artifacts:
            - build/**
      - step:
          name: Deploy to production
          script:
            - npm i -g firebase-tools
            - firebase deploy --token $FIREBASE_TOKEN --non-interactive --only firestore,hosting,storage
